#+TITLE: User Config
#+AUTHOR: Jan Roßbach
#+property: header-args:elisp :tangle ~/.config/spacemacsconf/user-config.el
#+STARTUP: overview

#+begin_src emacs-lisp :tangle yes
;; -*- lexical-binding: t; -*-
#+end_src

* Keybinds
  This section defines some custom Keybinds for sapcemacs.

** Bookmarks
This sets the SPC RET Binding to my Bookmarks similar to the Doom Emacs binding.
#+begin_src emacs-lisp :tangle yes
(spacemacs/set-leader-keys "RET" 'bookmark-jump)
(spacemacs/set-leader-keys "ob" 'spacemacs/bm-transient-state/body)
(spacemacs/set-leader-keys "om" 'bm-toggle)
(spacemacs/set-leader-keys "om" 'bm-toggle)
(spacemacs/set-leader-keys "on" 'bm-next)
(spacemacs/set-leader-keys "op" 'bm-previous)
(spacemacs/set-leader-keys "oc" 'bm-remove-all-all-buffers)
#+end_src

** Python
#+begin_src emacs-lisp :tangle yes
  (spacemacs/set-leader-keys-for-major-mode 'python-mode "se" 'python-shell-send-statement)
#+end_src

** Org Brain alternative keys
  #+begin_src emacs-lisp :tangle yes
    (with-eval-after-load 'org-brain (define-key org-brain-visualize-mode-map "i" 'link-hint-open-link))
    (spacemacs/set-leader-keys "oo" 'org-brain-agenda)
    (spacemacs/set-leader-keys "oA" 'org-brain-archive)
    (spacemacs/set-leader-keys "o:" 'org-brain-set-tags)
    (spacemacs/set-leader-keys "oR" 'org-brain-refile)
  #+end_src
  #+RESULTS:

** Fixme Mode
#+begin_src emacs-lisp :tangle yes
   ;(global-fixmee-mode 1)
  ; (spacemacs/set-leader-keys "of" 'fixmee-view-listing)
#+end_src

* Org Mode
** Capture
   This defines the [[https://orgmode.org/manual/Capture-templates.html#Capture-templates][Capture Templates]] for my config. Some are in hardcoded files, so be careful.
  #+begin_src emacs-lisp :tangle yes
    (setq org-capture-templates
          '(("t" "Todo" entry (file+headline "~/Dropbox/Org/brain/agenda.org" "Tasklist")
             "** TODO %?\n  %i\n")
            ("j" "Journal" entry (file+olp+datetree "~/Dropbox/Org/brain/journal.org")
             "* %?\nEntered on %U\n  %i\n")
            ("p" "Project" entry (file+headline "~/Dropbox/Org/brain/agenda.org" "Projects")
             "** %?\n %i\n")
            ("n" "Note" entry (file "~/Dropbox/Org/brain/inbox.org")
             "* %i")
            ("a" "Anki")
            ("ad" "Deep Learning" entry (file+headline "~/Dropbox/Org/brain/anki.org" "Deep Learning")
             (file "~/Dropbox/Org/templates/ankiTemplate.org"))
            ("am" "Model Checking" entry (file+headline "~/Dropbox/Org/brain/anki.org" "Model Checking")
             (file "~/Dropbox/Org/templates/ankiTemplate.org"))
            ("aa" "Approximative Algorithmen" entry (file+headline "~/Dropbox/Org/brain/anki.org" "Approximative Algorithmen")
             (file "~/Dropbox/Org/templates/ankiTemplate.org"))))
  #+end_src
** Notifications
  #+begin_src emacs-lisp :tangle yes
;;    (setq org-wild-notifier--day-wide-events t)
  #+end_src

** Babel
  This defines the languages that babel should load in order to evaluate src blocks.
#+begin_src emacs-lisp :tangle yes
  (setq org-confirm-babel-evaluate nil)
  (org-babel-do-load-languages
   'org-babel-load-languages
   '( (java  . t)
      (python  . t)
      (shell . t)
      (gnuplot . t)
      (clojure . t)
      (emacs-lisp . t)
      ))

  (setq org-babel-clojure-backend 'cider)
#+end_src

** ref
   First we configure where the files can be found.
#+begin_src emacs-lisp :tangle yes
  (setq bibtex-completion-bibliography '("~/Dropbox/Org/brain/Bachelorarbeit/Papers/refs.bib")
        bibtex-completion-library-path "~/Dropbox/Org/brain/Bachelorarbeit/Papers/"
        bibtex-completion-notes-path "~/Dropbox/Org/brain/Bachelorarbeit/Papers/notes.org")
#+end_src

This sets the pdf open process to use zathura.
#+begin_src emacs-lisp :tangle yes
  (setq org-ref-open-pdf-function
        (lambda (fpath)
          (start-process "zathura" "*helm-bibtex-zathura*" "/usr/bin/zathura" fpath)))
#+end_src

In Order to make sure that bibtex is called on our latex file when compiling it to pdf, we add the bibtex command into the list
of pdflatex commands that are run on the file. Otherwise citations are not going to work properly.

#+begin_src emacs-lisp :tangle yes
  (setq org-latex-pdf-process
        '("pdflatex -interaction nonstopmode -output-directory %o %f"
          "bibtex %b"
          "pdflatex -interaction nonstopmode -output-directory %o %f"
          "pdflatex -interaction nonstopmode -output-directory %o %f"))
#+end_src

** Org brain
   This enables getting to my Org brain files from any org document.
#+begin_src emacs-lisp :tangle yes
  (add-hook 'before-save-hook #'org-brain-ensure-ids-in-buffer)
#+end_src

** Roam

Setting up the home directory for org roam and turning on completion of Nodes.
#+begin_src emacs-lisp :tangle yes
  (setq org-roam-directory (file-truename "~/Dropbox/Org/roam/"))
  (setq org-roam-completion-everywhere t)
#+end_src

Org roam uses custom capture templates. Let's set them here. The semantics are similar to regular Org capture templates.

#+begin_src emacs-lisp :tangle yes
   (setq org-roam-capture-templates '(("d" "default" plain "%?" :target
                                       (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}"))
                                       ("p" "project" plain "* Goals\n\n%?\n\n* Tasks\n\n** TODO Add initial tasks\n\n* Dates\n\n"
                                        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+category: ${title}\n#+filetags: Project")
                                        :unnarrowed t)))
#+end_src

Then we define some custom functions. Org roam is a lot easier to hack on and customize than Org Brain because it is simpler out of the box.

#+begin_src emacs-lisp :tangle yes
  (defun org-roam-node-insert-immediate (arg &rest args)
    (interactive "P")
    (let ((args (cons arg args))
          (org-roam-capture-templates (list (append (car org-roam-capture-templates)
                                                    '(:immediate-finish t)))))
      (apply #'org-roam-node-insert args)))
#+end_src

#+begin_src emacs-lisp :tangle yes
(defun my/org-roam-filter-by-tag (tag-name)
  (lambda (node)
    (member tag-name (org-roam-node-tags node))))

(defun my/org-roam-list-notes-by-tag (tag-name)
  (mapcar #'org-roam-node-file
          (seq-filter
           (my/org-roam-filter-by-tag tag-name)
           (org-roam-node-list))))

(defun my/org-roam-refresh-agenda-list ()
  (interactive
  (setq org-agenda-files (my/org-roam-list-notes-by-tag "Project")))
;; Build the agenda list the first time for the session
(my/org-roam-refresh-agenda-list)
#+end_src

#+begin_src emacs-lisp :tangle yes
  (defun my/org-roam-project-finalize-hook ()
    "Adds the captured project file to `org-agenda-files' if the
  capture was not aborted."
    ;; Remove the hook since it was added temporarily
    (remove-hook 'org-capture-after-finalize-hook #'my/org-roam-project-finalize-hook)

    ;; Add project file to the agenda list if the capture was confirmed
    (unless org-note-abort
      (with-current-buffer (org-capture-get :buffer)
        (add-to-list 'org-agenda-files (buffer-file-name)))))

  (defun my/org-roam-find-project ()
    (interactive)
    ;; Add the project file to the agenda after capture is finished
    (add-hook 'org-capture-after-finalize-hook #'my/org-roam-project-finalize-hook)

    ;; Select a project file to open, creating it if necessary
    (org-roam-node-find
     nil
     nil
     (my/org-roam-filter-by-tag "Project")
     :templates
     '(("p" "project" plain "* Goals\n\n%?\n\n* Tasks\n\n** TODO Add initial tasks\n\n* Dates\n\n"
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+category: ${title}\n#+filetags: Project")
        :unnarrowed t))))

  (org-roam-node-tags (first (org-roam-node-list)))
#+end_src

Now we have all the functions we will need for the setup.
Let's now set up the hotkeys in the user space under a new prefix r.
#+begin_src emacs-lisp :tangle yes
  (spacemacs/declare-prefix "or" "org-roam")
  (spacemacs/set-leader-keys "ord" 'org-id-get-create)
  (spacemacs/set-leader-keys "orf" 'org-roam-node-find)
  (spacemacs/set-leader-keys "ori" 'org-roam-node-insert)
  (spacemacs/set-leader-keys "ora" 'org-roam-alias-add)
  (spacemacs/set-leader-keys "orI" 'org-roam-node-insert-immediate)
  (spacemacs/set-leader-keys "orp" 'my/org-roam-find-project)
  (spacemacs/set-leader-keys "ort" 'org-roam-dailies-goto-today)
#+end_src

#+RESULTS:

** Agenda
*** TODO-SEQ
   Setting the keyword Sequenze for todo keywords.
#+begin_src emacs-lisp :tangle yes
  (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "WAITING(w@)" "|" "DONE(d!)" "CANCELLED(c@)" "DEFERRED(f@)")))
#+end_src
*** Archive
    Set the archive Location globally to the current archive.
   #+begin_src emacs-lisp :tangle yes
     ;;(setq org-archive-location "~/Dropbox/archive/myarchive.org")
   #+end_src
*** Inbox
    Lets first define a custom function to get to the inbox quickly from anywhere and bind it to
    a spacemacs user command.
   #+begin_src emacs-lisp :tangle yes
     (setq gtd/inbox-file-path "~/Dropbox/Org/brain/inbox.org")

     (defun go-to-inbox-buffer ()
       (interactive)
       (find-file gtd/inbox-file-path))

     (spacemacs/set-leader-keys "oi" 'go-to-inbox-buffer)
   #+end_src
*** Files

Here is a Place to hard code some files we want to have in the agenda in addition to the ones added automatically.
#+begin_src emacs-lisp :tangle yes
  (push "~/Dropbox/Org/brain/habits.org" org-agenda-files)
  (push "~/Dropbox/Org/brain/agenda.org" org-agenda-files)
  (push "~/Dropbox/Org/brain/inbox.org" org-agenda-files)
#+end_src

*** Super agenda

    Here I set my GTD view with the help of the org-super-agenda package.

   #+begin_src emacs-lisp :tangle yes
     (setq spacemacs-theme-org-agenda-height nil
           org-agenda-time-grid '((daily today require-timed) (800 1000 1200 1400 1600 1900 2000) "......." "----------------------")
           org-agenda-skip-scheduled-if-done t
           org-agenda-skip-deadline-if-done t
           org-agenda-include-deadlines t
           org-agenda-include-diary t
           org-agenda-block-separator nil
           org-agenda-compact-blocks t
           org-agenda-start-with-log-mode t)

     (setq org-agenda-custom-commands
           '(("o" "GTD View"
              ((agenda "" ((org-agenda-span 'day)
                           (org-super-agenda-groups
                            '((:name "Today"
                                     :time-grid t
                                     :date today
                                     :todo "TODAY"
                                     :scheduled today
                                     :order 1)))))
               (alltodo "" ((org-agenda-overriding-header "")
                            (org-super-agenda-groups
                             '((:name "Next to do"
                                      :todo "NEXT"
                                      :order 1)
                               (:name "Done"
                                      :todo "DONE"
                                      :order 3)
                               (:name "Important"
                                      :tag "Important"
                                      :priority "A"
                                      :order 6)
                               (:name "Due Today"
                                      :deadline today
                                      :order 2)
                               (:name "Due Soon"
                                      :deadline future
                                      :order 8)
                               (:name "Overdue"
                                      :deadline past
                                      :order 7)
                               (:name "Assignments"
                                      :tag "Assignment"
                                      :order 10)
                               (:name "Issues"
                                      :tag "Issue"
                                      :order 12)
                               (:name "Projects"
                                      :tag "Project"
                                      :order 14)
                               (:name "Emacs"
                                      :tag "Emacs"
                                      :order 13)
                               (:name "Research"
                                      :tag "Research"
                                      :order 15)
                               (:name "To read"
                                      :tag "Read"
                                      :order 30)
                               (:name "Waiting"
                                      :todo "WAITING"
                                      :order 20)
                               (:name "trivial"
                                      :priority<= "C"
                                      :tag ("Trivial" "Unimportant")
                                      :todo ("SOMEDAY" )
                                      :order 90)
                               (:discard (:tag ("Chore" "Routine" "Daily")))))))))))
   (org-super-agenda-mode 1)
   #+end_src

** Projects
   Projectile has some functionality to capture todos for the current project in an Org file. It is stored by default in a file called TODOS.org in the project root.
   This Code here is to add these files to the Org Agenda.
#+BEGIN_SRC emacs-lisp :tangle yes
  (with-eval-after-load 'org-agenda
    (require 'org-projectile)
    (mapcar #'(lambda (file)
                   (when (file-exists-p file)
                     (push file org-agenda-files)))
            (org-projectile-todo-files)))
  ;; (with-eval-after-load 'org-agenda
  ;;   (require 'org-projectile)
  ;;   (push (org-projectile:todo-files) org-agenda-files))
#+END_SRC

* Misc
  In this section, there are various little adjustments to same packages that do not warrent a specific section.

** Tabs
  Turn on tab mode by default and set the new tab choice to the home buffer.
 #+begin_src emacs-lisp :tangle yes
   ;; (tab-bar-mode 1)
   ;; (setq tab-bar-new-tab-choice "*spacemacs*")
 #+end_src

** Neotree

#+begin_src emacs-lisp :tangle yes
  (setq neo-theme 'icons)
  (setq neo-window-position 'right)
#+end_src

** Openwith
   The openwith package provides support for what file types should be opended with which programs.
   I am mostly happy with the defaults, but I want to view pdfs with zathura.
#+begin_src emacs-lisp :tangle yes
  (openwith-mode t)
  (setq openwith-associations '(("\\.pdf\\'" "zathura" (file))))
#+end_src
** Emacs comp-native
   This setting disables the constant compiler warnings in the emacs-native-comp version of emacs.
#+begin_src emacs-lisp :tangle yes
  ;;(setq comp-async-report-warnings-errors nil)
#+end_src
** Transparency
   Enables/Disables transparency at startup. Use the spacemacs/toggle-transparency to change it afterwards.
#+begin_src emacs-lisp :tangle yes
  (spacemacs/enable-transparency)
#+end_src
** Popper
#+begin_src emacs-lisp :tangle yes
  ;; (setq popper-reference-buffers
  ;;      '("\\*Messages\\*"
  ;;        "\\*Warnings\\*"
  ;;         "Output\\*"
  ;;         help-mode
  ;;         messeges-mode
  ;;         compilation-mode))
  ;; ;(setq popper-group-function #'popper-group-by-projectile)
  ;; (global-set-key (kbd "C-ß") 'popper-toggle-latest)
  ;; (global-set-key (kbd "M-ß") 'popper-cycle)
  ;; (spacemacs/set-leader-keys "wpt" 'popper-toggle-type)
  ;; (spacemacs/set-leader-keys "wpc" 'popper-cycle)
  ;; (spacemacs/set-leader-keys "wpl" 'popper-toggle-latest)
#+end_src
** evil-Better-jumper
This variable prevents the C-i hotkey to behave like Tab in the gui version of emacs.
#+begin_src emacs-lisp :tangle yes
 (setq dotspacemacs-distinguish-gui-tab t)
#+end_src
